### ISSUE TITLE
Support multiple bulbs and multi-color setups

### ISSUE THREAD

**Issue by eidermar** [GordonDiggs/lifx-esb#1]
This is so cool. I was just yesterday joking with a buddy that someone should do this. Boom, there you go. 
If you want to go further with this I'd love to see support for multiple bulbs and also the multi-color setups the ESB has most of the times. Kind of like themes or scenes I guess.

Thanks for sharing this!

**Comment by gdiggs** [comment]
@eidermar Thanks! Glad you like it! it supports multiple colors! The API will return them and it will cycle through them [here](https://github.com/GordonDiggs/lifx-esb/blob/master/bin/lifx-esb#L18-L21). Multiple bulb support would be cool!
